project_id = "ofcktyrnwvlfiqnnhkoc"

[functions.analyze-cognitive-quiz]
verify_jwt = false

[functions.generate-cognitive-insights]
verify_jwt = false

[functions.analyze-couple-compatibility]
verify_jwt = false

[functions.create-profile]
verify_jwt = false
